# Generated by Django 3.2.5 on 2021-08-10 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libros_autores_template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='desc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
