# Generated by Django 3.2.5 on 2021-08-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_autores_template', '0002_authors_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='books_authors', to='libros_autores_template.books'),
        ),
    ]
