# Generated by Django 3.2.5 on 2021-08-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_autores_template', '0005_auto_20210812_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='libros_autores_template.Books'),
        ),
    ]
